### PR TITLE
Correct handeling of NZBGet permissions fixing

### PR DESCRIPTION
**Pull request by Safihre**
Now it actually works as expected :)

### CODE REVIEW

**Comment by ymartin59** [comment]
Hello. `sudo` is not available on DSM 5 and `set_syno_permissions` has to be fixed to avoid weird things I reported.

**Comment by Safihre** [comment]
Then maybe the `wget` also needs to be performed using `su`, because right now it won't work due to the permissions error.
I still don't understand what these `set_syno_permissions` problems are, as long as the ACL is applied correctly.

**Comment by ymartin59** [comment]
OK ACL is applied but previous standard Unix permissions are completely discarded according to `ls -l`.
DSM 6 allows to declare additional scripts to run as user, but it does not help with DSM 5 support.
I guess `chown` file after `wget` is far enough.

**Comment by Safihre** [comment]
@ymartin59 It's not working. The permissions of the file is not the problem, `su` is the problem.
Are you sure `su` is working like this on DSM6? Or should we do some DSM5 / 6 specific thing?
I tried it also via SSH (the installer did the `chown`) but nothing is working. Always `Permission denied`, even when trying to run a simple `ls`:

image

**Comment by Safihre** [comment]
Problem solved, it required `chmod +x`.
Now it works!

**Comment by ymartin59** [comment]
@Safihre Thanks. I will test and review. Just an advice: when using `--amend` commit option, think about enabling `--reset-author` so that timestamp is updated - helps others to know if "comments" are already included there.

**Pull request merged**
